# Generated by Django 6.0.2 on 2026-02-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('vintage', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('wineProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.wineproducer')),
            ],
        ),
    ]
