# Generated by Django 6.0.2 on 2026-02-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_wine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Created_At', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=300)),
                ('Brand', models.CharField(max_length=300)),
                ('Cost', models.CharField(max_length=300)),
                ('Size', models.CharField(max_length=300)),
                ('Mouth_Size', models.CharField(max_length=300)),
                ('Color', models.CharField(max_length=300)),
                ('Current_Quantity', models.CharField(max_length=300)),
                ('Supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
        migrations.DeleteModel(
            name='WineProducer',
        ),
    ]
