# Generated by Django 6.0.2 on 2026-02-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0003_supplier_waterbottle_delete_wine_delete_wineproducer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='Cost',
            field=models.IntegerField(),
        ),
    ]
