# Generated by Django 6.0.2 on 2026-02-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0004_alter_waterbottle_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='Current_Quantity',
            field=models.IntegerField(),
        ),
    ]
