# Generated by Django 6.0.3 on 2026-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0005_alter_waterbottle_current_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
